Todos/Todos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todoapp/', include('todoapp.urls'))
]

Todos/todoapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'todoapp'

urlpatterns = [
    path('', signin),
    path('user/', user, name="user"),
    path('insert/',insert, name="insert"),
    path('signup/', signup_view, name = 'signup'),
    path('logout/', logout),
    path('delete/<id>', delete, name='delete'),
]

Todos/todoapp/models.py
from django.db import models
# from .views import*
from django.contrib.auth.models import User


class Task(models.Model):
    Title = models.CharField(max_length=200)
    Time = models.DateField(auto_now_add=True)
    # status = models.CharField(max_length=100)
    Task_type = (
        ('l', 'Longterm'),
        ('s', 'shortterm'),
     )
    type = models.CharField(max_length=1, choices=Task_type)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    


    def __str__(self):
        return self.Title

Todos/todoapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login
import datetime
from django.contrib import messages
from  .models import Task

import todoapp.models




def signin (request):
    if request.method == "POST":
        uname = request.POST["username"]
        pwd1 = request.POST['pwd']
        
        user = authenticate(request,username=uname,password=pwd1)
        if user is not None:
            login(request,user)
            return redirect('http://localhost:8000/todoapp/user/')
        else:
            messages.error(request,"Invalid Credentials")
            return redirect('http://localhost:8000/todoapp/')
    else:
        return render(request, 'todoapp/login.html')
    


def logout(request):
    auth.logout(request)
    return redirect("todoapp.html")



def signup_view(request):

    if request.method == "POST":
        name = request.POST["name"]
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if pass1 == pass2:
            if User.objects.filter(username=name).exists():
                messages.info(request,"Username Aready in Use")
                return redirect('http://localhost:8000/todoapp/signup/')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"Email ID Aready in Use")
                return redirect('http://localhost:8000/todoapp/signup/')
            else:
                user = User.objects.create_user(username=name,password=pass1,email=email)
                user.save()
                messages.info(request,"User Registered")
                return redirect("http://localhost:8000/todoapp/")
        else:
            messages.info(request,"Both Password and Confirm password are not matching")
            return render(request, 'todoapp/signup.html')
    else:
        return render(request,'todoapp/signup.html')



def user(request):
    alltasks = Task.objects.filter(user=request.user)
    context = {'alltasks':alltasks}
    return render(request,'todoapp/user.html',context)

    


def insert(request):
    if request.method == 'POST':
       
        Title = request.POST['Title']
        Time = request.POST['Time']
        # status = request.POST['status']
        type2 = request.POST['Task_type']
        tasks =Task.objects.create( user=request.user,Title=Title, Time=Time ,type=type2)
        tasks.save()
        return redirect('todoapp:user')
    else:
        return render(request,'todoapp/insert.html')

    return render(request,'todoapp/insert.html')
    




def delete(request, id):
    task = todoapp.models.Task.objects.get(id=id)
    task.delete()
    return redirect('todoapp:user')

Todos/templates/todoapp/delete.html
<p> Are You sure you wanna delete '{{item}}'</p>

<a href="{% url 'list %} ">cancel</a>

<form method ="POST" action=''>
    <input type ="submit" name = 'confirm'>
</form>

Todos/templates/todoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

    <div class="main">

        <!-- Sign up form -->
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="register-form">
                            <div class="form-group">
                                <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="name" id="name" placeholder="Your Name"/>
                            </div>
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"></i></label>
                                <input type="email" name="email" id="email" placeholder="Your Email"/>
                            </div>
                            <div class="form-group">
                                <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="pass" id="pass" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                <input type="password" name="re_pass" id="re_pass" placeholder="Repeat your password"/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                                <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="images/signup-image.jpg" alt="sing up image"></figure>
                        <a href="#" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </section>

        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="images/signin-image.jpg" alt="sing up image"></figure>
                        <a href="#" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="login-form">
                            <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="your_name" id="your_name" placeholder="Your Name"/>
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="your_pass" id="your_pass" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                            </div>
                        </form>
                        <div class="social-login">
                            <span class="social-label">Or login with</span>
                            <ul class="socials">
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

Todos/templates/todoapp/insert.html
<html>
    <head>
        <title> Add task </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"rel="stylesheet"
    </head>
    <body class = 'bg-light'>
        <div class="container">
            <div class="row mt-5">
                <div class="col-md-8 offset-md-2">
                    <div class="card">
                        <div class="card-header shawdow-sm bg-white">
<h1 class="display-5 text-info"><i class="fas fa-check-double"></i>Todos</h1>                           
                        </div>
<body>
    <form action='http://localhost:8000/todoapp/insert/' method="POST">
        {% csrf_token %}
        <label for="Title"> Enter your task title :  </label>
        <input type="text" id= "Title" name="Title" placeholder="Enter the task...."><br><br>

        <label for="Time">  Time Schedule :  </label>
        <input type="date" id= "Time" name="Time" pattern=""><br><br>



        <!-- <label for="status"> Status :  </label>
        <input type="text" id="status" name="status" ><br><br> -->
       
        <!-- <select id="status" name="status">
            <option value="t">Pending</option>
            <option value="f">Completed </option> -->
    
        <select id="Task_type" name="Task_type">
        <option value="Shortterm Goals">Shortterm Goals</option>
        <option value="Longterm Goals">Longterm Goals</option>




        
    </select>
    <br>
    <br>
    <br>
    <button type ="submit" > Add </button>
    </form>
    
    
    

</body>
</html>

Todos/templates/todoapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo sign</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'todoapp/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'todoapp/css/style.css' %}">
</head>
<body>
    <section class="sign-in">
        <div class="container">
            <div class="signin-content">
                <div class="signin-image">
                    <figure><img src="{% static 'todoapp/images/signin-image.jpg' %}" alt="sign in image"></figure>
                    <a href="http://localhost:8000/todoapp/signup" class="signin-image-link">Create an account</a>
                </div>

                <div class="signin-form">
                    <h2 class="form-title"> Todo login</h2>

                    <form action ='http://localhost:8000/todoapp/' method="POST" class="register-form" id="login-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            <input type="text" name="username" id="username" placeholder="Name"/>
                        </div>
                        <div class="form-group">
                            <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="pwd" id="pwd" placeholder="Password"/>
                        </div>
                        <!-- <div class="form-group">
                            <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                            <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                        </div> -->
                        <div class="form-group form-button">
                            <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                        </div>
                    </form>
                    {% for message in messages %}
                          <p style="color:red;"> {{message}} </p>
                    {% endfor %}
                    <!-- <div class="social-login">
                        <span class="social-label">Or login with</span>
                        <ul class="socials">
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                        </ul>
                    </div> -->
                </div>
            </div>
        </div>
    </section>

</body>
<script src="{% static 'todoapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'todoapp/js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

Todos/templates/todoapp/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'todoapp/fonts/material-icon/css/material-design-iconic-font.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'todoapp/css/style.css' %}">
</head>
<body>

    <div class="main">

        <!-- Sign up form -->
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title"> Todo Sign up</h2>
                        <form  action = "{% url 'todoapp:signup' %}"method="POST" class="register-form" id="register-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="name" id="name" placeholder=" Name"/>
                            </div>
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"></i></label>
                                <input type="email" name="email" id="email" placeholder=" Email"/>
                            </div>
                            <div class="form-group">
                                <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="pass1" id="pass1" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                <input type="password" name="pass2" id="pass2" placeholder="Repeat password"/>
                            </div>
                            
                            <!-- <div class="form-group">
                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                                <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                            </div> -->
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                        {% for message in messages %}
                          <p style="color:red;"> {{message}} </p>
                        {% endfor %}
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'todoapp/images/signup-image.jpg' %}" alt="sing up image"></figure>
                        <a href="http://localhost:8000/todoapp" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </section>
</div>
</body>
<script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

Todos/templates/todoapp/user.html
<html>
    <head>
        <title> User Login </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"rel="stylesheet">
    </head>
    <body class = 'bg-light'>
        <form action="http://127.0.0.1:8000/todoapp/" >
            <input type="submit" style="float: right;color: rgb(16, 17, 16);" value="Logout">
        </form>
        
        <!-- <a href="http://127.0.0.1:8000/todoapp/" style="float:right;color: black;">logout</a>                     -->

        <div class="container">
            <div class="row mt-5">
                <div class="col-md-8 offset-md-2">
                    <div class="card">
                        <div class="card-header shawdow-sm bg-light">
<h1 class="display-10 text-info"><i class="fas fa-check-double"></i>{{user}} Todos</h1> 
                        </div>
                            
                        <div class="card-body">
                            <!-- <form action="http://localhost:8000/todoapp/insert/" method='POST'>
                                {% csrf_token %} -->
                                <div class="input-group">
                                    <p> your tasks are listed below </p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<br><br><br>
                                    <hr>
                                    <div class="input-group-append text-info">
                                        <span class="input-group-text bg-white py-0">
                                            <a href="{% url 'todoapp:insert' %}" style="float: right;column-width: auto;">Add Task</a>
                                            <!-- <button type="submit" class="btn btn-sm text-info">
                                                <i class="fa fa-plus-circle fa-lg"></i>
                                            </button> -->
                                        </span>
                                    </div>
                                </div>
                                
                            </form>
                            <ul class="list-group">
                                {% for a in alltasks %}
                                <!-- {{ a.id}}. -->
                                <b>Task Title:</b> {{ a.Title}}<br> 
                                <b>Task created Time:</b>{{ a.Time }}<br> 
                                <b>Task Status: </b> {{a.type}}<br>
                                
                                <!-- {% if a.status %} 
                                <p> Completed </p>
                                {% else %}
                                <p> pending </p>
                                {%  endif %} --> 
                                
                                <a style="color: blue;" href="{% url 'todoapp:delete' id=a.id %}">Delete</a>
                                <hr>
                            </form>
                                {% empty %}
                                <i class="list-group">
                                    <span class="font-italic"> No Task added </span>
                                </i>
                                {% endfor %}
                                
                                
                                
                                        
                                    
                                    
                                </ul>
                                
                         
                            </ul> 
                        </div>
                    </div>
                </div>
             </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </body>
</html>